name: Security Audit

on:
  schedule:
    - cron: "0 2 * * 1" # Weekly on Monday at 2 AM
  workflow_dispatch:

jobs:
  security-audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit safety semgrep

      - name: Run Bandit security check
        run: |
          bandit -r app -f json -o bandit-report.json
          bandit -r app -f txt

      - name: Run Safety check
        run: |
          safety check --json --output safety-report.json
          safety check

      - name: Run Semgrep security scan
        run: |
          semgrep --config=auto app --json --output=semgrep-report.json
          semgrep --config=auto app

      - name: Upload security reports
        uses: actions/upload-artifact@v3
        with:
          name: security-audit-reports
          path: |
            bandit-report.json
            safety-report.json
            semgrep-report.json

      - name: Create security issue on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Security Audit Failed',
              body: 'The weekly security audit has detected potential security issues. Please review the security reports.',
              labels: ['security', 'bug']
            })
